# Generated by Django 2.0.1 on 2018-01-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Товар')),
                ('description', models.TextField(verbose_name='Описание')),
                ('foto', models.URLField(verbose_name='Интернет-адрес')),
            ],
        ),
    ]
