# Generated by Django 2.0.1 on 2018-01-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productswarehouse',
            name='articals',
            field=models.IntegerField(default=0, verbose_name='Код товара'),
        ),
    ]
