# Generated by Django 2.0.1 on 2018-01-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productswarehouse_articals'),
    ]

    operations = [
        migrations.AddField(
            model_name='productswarehouse',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена товара'),
        ),
    ]
