# Generated by Django 2.0.1 on 2018-01-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productswarehouse_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productswarehouse',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
