# Generated by Django 2.0.1 on 2018-01-08 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180107_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellsWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.CharField(max_length=2, verbose_name='Ряд')),
                ('cell', models.CharField(max_length=3, verbose_name='Ячейка')),
                ('levelCell', models.CharField(max_length=3, verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Ячейка',
                'verbose_name_plural': 'Ячейки',
            },
        ),
        migrations.AddField(
            model_name='productswarehouse',
            name='cells_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.CellsWarehouse'),
        ),
    ]
