# Generated by Django 2.0.1 on 2018-01-08 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180108_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellsWarehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.CellsWarehouse')),
            ],
        ),
        migrations.RemoveField(
            model_name='productswarehouse',
            name='cells_warehouse',
        ),
        migrations.AddField(
            model_name='storage',
            name='productsWarehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductsWarehouse'),
        ),
    ]
