# Generated by Django 2.0.1 on 2018-01-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180108_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': 'Место хранения', 'verbose_name_plural': 'Места хранения'},
        ),
        migrations.AddField(
            model_name='cellswarehouse',
            name='name',
            field=models.CharField(default=0, max_length=10, verbose_name='Уровень'),
        ),
    ]
