# Generated by Django 2.0.1 on 2018-01-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180108_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='name',
            field=models.CharField(default=0, max_length=10, verbose_name='Место хранения'),
        ),
    ]
