# Generated by Django 2.0.1 on 2018-01-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_storage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
